import './App.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin,AiFillYoutube,AiFillFacebook} from 'react-icons/ai'

import userimg from './images/user.jpg'
import design from './images/design.png'
import consulting from './images/consulting.png'
import code from './images/code.png'
import web1 from './images/web1.png'
import web2 from './images/web2.png'
import web3 from './images/web3.png'
import web4 from './images/web4.png'
import web5 from './images/web5.png'
import web6 from './images/web6.png'
import { useState } from 'react'

export default function App() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <head>
        <title>Mhioul's Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">WELCOME</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Mhioul Mohamed Amine
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Step into a realm of digital artistry and innovation – my portfolio. Explore a collection that brings together design, functionality, and imagination, showcasing my expertise in crafting exceptional websites. Join me in turning ideas into immersive web experiences that leave a lasting impact.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
              <AiFillFacebook/>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <img src={userimg} />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Discover My Offered Services  From <span className='text-teal-500'> web development</span> and <span className='text-teal-500'>design</span> to marketing strategies, I bring your ideas to life. Let's collaborate and make your vision a reality :
            </p>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <img src={design} width={100} height={100} className='mx-auto'/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
              In this creative haven, I'm meticulously sculpting elegant designs that blend beauty and functionality seamlessly. Every stroke and element converges to create a harmonious visual symphony, inviting the world to explore innovation through the lens of exquisite design.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <ul>
                    <li className='text-gray-800 py-1'>Adobe Creative Suite (Photoshop, Illustrator, XD)</li>
                    <li className='text-gray-800 py-1'>Sketch</li>
                    <li className='text-gray-800 py-1'>Figma</li>
                    <li className='text-gray-800 py-1'>InVision</li>
                </ul>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                <img src={code} width={100} height={100} className='mx-auto'/>
                <h3 className="text-lg font-medium pt-7 pb-2  dark:bg-white">Coding</h3>
                <p className="py-2  dark:bg-white">
                  In this realm of logic and creativity, I'm weaving intricate code that powers digital experiences with finesse.
                  Each line and algorithm merges to craft a seamless functionality, inviting exploration of innovation through elegant code.
                </p>
                <h4 className="text-teal-600 py-4  dark:bg-white">Technologies I use</h4>
                <ul>
                  <li className="text-gray-800 py-1  dark:bg-white">JavaScript (ES6+)</li>
                  <li className="text-gray-800 py-1  dark:bg-white">React</li>
                  <li className="text-gray-800 py-1  dark:bg-white">Node.js</li>
                  <li className="text-gray-800 py-1  dark:bg-white">HTML5 & CSS3</li>
                 <li className="text-gray-800 py-1  dark:bg-white">Git & Version Control</li>
                </ul>
              </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <img src={consulting} width={100} height={100} className='mx-auto'/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
              Amidst this creative domain, I intricately craft consulting excellence, fusing insight and effectiveness. Each facet merges, creating a symphony of guidance, inviting exploration through unparalleled expertise.
              </p>
              <h4 className="py-4 text-teal-600">Consulting domains</h4>
              <ul>
                    <li className='text-gray-800 py-1'>    Management Consulting</li>
                    <li className='text-gray-800 py-1'>Marketing Consulting</li>
                    <li className='text-gray-800 py-1'>Human Resources Consulting</li>
                    
                </ul>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Hey there! I'm <span className='text-teal-500'>Mhioul Mohamed Amine</span>, a passionate Full Stack Web Developer. With a love for both coding and design, I craft digital solutions that marry functionality with aesthetics. My journey involves translating innovative ideas into lines of code, and I thrive on the challenges that each project brings. Let's collaborate and bring your ideas to life!
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <img
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}